# Note
# DO NOT add [target.thumbv6m-none-eabi] or [target.thumbv8m.main-none-eabihf]
# or any other [target.<triple>] configurations here, since they are already provided by
# /.cargo/config.toml (ie in the root)
#
# If the targets are also added here, the build will fail because
# the link args (ie link-arg=-Tlink.x) will be set twice.
#
# It is fine to add [alias]es here.

# Example-specific aliases

[alias]

# Invoke using cargo check-rp2040
check-rp2040 = [
    "check",
    "--target", "thumbv6m-none-eabi",
    "--no-default-features",
    "--features",
    "rp2040"
]

# Invoke using cargo build-rp2040
build-rp2040 = [
    "build",
    "--target", "thumbv6m-none-eabi",
    "--no-default-features",
    "--features",
    "rp2040"
]

# Invoke using:
# cargo run-rp2040 --bin lsm6ds-rp-i2c
# cargo run-rp2040 --bin lsm6ds-rp-spi
run-rp2040 = [
    "run",
    "--target", "thumbv6m-none-eabi",
    "--no-default-features",
    "--features", "rp2040"
]

# Invoke using cargo check-rp235xa
check-rp235xa = [
    "check",
    "--target", "thumbv8m.main-none-eabihf",
    "--no-default-features",
    "--features",
    "rp235xa"
]

# Invoke using cargo build-rp235xa
build-rp235xa = [
    "build",
    "--target", "thumbv8m.main-none-eabihf",
    "--no-default-features",
    "--features",
    "rp235xa"
]

# Invoke using:
# cargo run-rp235xa --bin lsm6ds-rp-i2c
# cargo run-rp235xa --bin lsm6ds-rp-spi
run-rp235xa = [
    "run",
    "--target", "thumbv8m.main-none-eabihf",
    "--no-default-features",
    "--features", "rp235xa"
]